### PR TITLE
Adds User-Agent header to _fetch

### PR DESCRIPTION
**Pull request by gschorkopf**
Full disclosure: I'm not great at Python! Be gentle 😄

We're trying to add a header for "User-Agent", with the egg name and version. I've moved version out into it's own file to be reused in multiple places.

Additionally, we want to add this to all requests to Fastly. I'm not sure if _fetch is the best place to put this, if there are additional methods that add headers. Any suggestions?

### CODE REVIEW

**Comment by copyconstruct** [comment]
@gschorkopf Sorry for this super dilatory response - but would be happy to merge if you could rebase off of the latest master.

**Comment by gschorkopf** [comment]
Happy to! There you go.

**Comment by gschorkopf** [comment]
Oof apologies, my editor trims trailing whitespace. If you'd like I can get rid of those diffs.

**Comment by copyconstruct** [comment]
Thanks! Have merged.

**Pull request merged**
